apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: kubeconfig
  data:
    kubeconfig: |
          apiVersion: v1
          clusters:
          users:
          - name: admin
            user:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: nginx-config
  data:
    nginx.conf: |
      events {
          worker_connections 1024;
      }
      http {
        sendfile on;
        server {
          listen 8080;
          location / {
            gzip off;
            default_type text/plain;
            root /data/http;
          }
        } 
      }
- apiVersion: v1
  kind: ReplicationController
  metadata:
    labels:
      name: web-server-rc
    name: web-server-rc
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          name: web-server-rc
      spec:
        containers:
        - name: nginx
          image: quay.io/openshifttest/nginx-alpine@sha256:f266733786efb10c4353d4b44ada6f22434e983d22f0975d20803f1817d38f56
          volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/
          - name: kubeconfig
            mountPath: /data/http/      
        volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: kubeconfig
          configMap:
            name: kubeconfig
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: service-unsecure
    name: service-unsecure
  spec:
    ports:
    - name: http
      port: 27017
      protocol: TCP
      targetPort: 8080
    selector:
      name: web-server-rc
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      name: kubeconfig-route
    name: kubeconfig-route
  spec:
    port:
      targetPort: http
    to:
      kind: Service
      name: service-unsecure
      weight: 100
    wildcardPolicy: None




